export default {
  SEND_INVITATION_STARTED: 'SEND_INVITATION_STARTED',
  SEND_INVITATION_SUCCESS: 'SEND_INVITATION_SUCCESS',
  SEND_INVITATION_FAILED: 'SEND_INVITATION_FAILED',
  VALUE_CHANGED: 'VALUE_CHANGED',

  WS_INVITATION_INITIATED: 'WS_INVITATION_INITIATED',
  WS_INVITATION_DELIVERED: 'WS_INVITATION_DELIVERED',
  WS_INVITATION_RECIEVED: 'WS_INVITATION_RECIEVED',
  WS_INVITATION_ACCEPTED: 'WS_INVITATION_ACCEPTED',
  WS_INVITATION_DECLINE: 'WS_INVITATION_DECLINE',
};
