export default {
  SEND_INVITATION_STARTED: 'SEND_INVITATION_STARTED',
  SEND_INVITATION_SUCCESS: 'SEND_INVITATION_SUCCESS',
  SEND_INVITATION_FAILED: 'SEND_INVITATION_FAILED',
  VALUE_CHANGED: 'VALUE_CHANGED',
};
