export default {
    INIT_FORM_VALIDATION_STATE: 'INIT_FORM_VALIDATION_STATE',
    RESET_VALIDATION_STATE: 'RESET_VALIDATION_STATE',
    INPUT_BLURRED: 'INPUT_BLURRED',
    INPUT_FOCUSED: 'INPUT_FOCUSED',
  
    SERVER_VALIDATION: 'SERVER_VALIDATION',
    CLIENT_VALIDATION:'CLIENT_VALIDATION',
  
    INC_INPUT_COUTN :'INC_INPUT_COUTN'
  };
  