export default {
  WEBSOCKET_INITIALIZED: "WEBSOCKET_INITIALIZED",
  MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
  CONNECTION_STATE_CHANGED: "CONNECTION_STATE_CHANGED",
  SOCKET_ERROR: "SOCKET_ERROR",
  CLOSED_WEBSOCKET: "CLOSED_WEBSOCKET",
  URL_CHANGED: "URL_CHANGED",
};
