export default {
  SEND_INVITATION_STARTED: 'SEND_INVITATION_STARTED',
  SEND_INVITATION_SUCCESS: 'SEND_INVITATION_SUCCESS',
  SEND_INVITATION_FAILED: 'SEND_INVITATION_FAILED',

  ACCEPT_INVITATION_STARTED: 'ACCEPT_INVITATION_STARTED',
  ACCEPT_INVITATION_SUCCESS: 'ACCEPT_INVITATION_SUCCESS',
  ACCEPT_INVITATION_FAILED: 'ACCEPT_INVITATION_FAILED',

  DECLINE_INVITATION_STARTED: 'DECLINE_INVITATION_STARTED',
  DECLINE_INVITATION_SUCCESS: 'DECLINE_INVITATION_SUCCESS',
  DECLINE_INVITATION_FAILED: 'DECLINE_INVITATION_FAILED',

  FETCH_INVITATIONS_STARTED: 'FETCH_INVITATIONS_STARTED',
  FETCH_INVITATIONS_SUCCESS: 'FETCH_INVITATIONS_SUCCESS',
  FETCH_INVITATIONS_FAILED: 'FETCH_INVITATIONS_FAILED',

  OPEN_INVITATION: 'OPEN_INVITATION',
  CLOSE_INVITATION: 'CLOSE_INVITATION',
};
