export default {
  FETCH_HANGOUT_STARTED: "FETCH_HANGOUT_STARTED",
  FETCH_HANGOUT_SUCCESS: "FETCH_HANGOUT_SUCCESS",
  FETCH_HANGOUT_FAILED: "FETCH_HANGOUT_FAILED",

  SEARCH_INPUT_CHANGED: "SEARCH_INPUT_CHANGED",

  MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
  SOCKET_ERROR: "SOCKET_ERROR",
  CONNECTING: "CONNECTING",
  OPEN: "OPEN",
  CLOSING: "CLOSING",
  CLOSED: "CLOSED",
  SOCKET_READY: "SOCKET_READY",
};
