export const actionTypes = {
    SET_SOCKET: 'SET_SOCKET',
    LOAD_HANGOUTS: 'LOAD_HANGOUTS',
    LOAD_MESSAGES: 'LOAD_MESSAGES',
    FILTER_HANGOUT: 'FILTER_HANGOUT',
    SELECTED_HANGOUT: 'SELECTED_HANGOUT',
    HANGOUT_STATE_CHANGED: 'HANGOUT_STATE_CHANGED',


    FETCH_STARTED: 'FETCH_STARTED',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_FAILED: 'FETCH_FAILED',

    ONLINE_STATE_CHANGED: 'ONLINE_STATE_CHANGED',


    OFFER_STARTED: 'OFFER_STARTED',
    OFFER_SUCCESS: 'OFFER_SUCCESS',
    OFFER_FAILED: 'OFFER_FAILED',

    ACCEPT_STARTED: 'ACCEPT_STARTED',
    ACCEPT_SUCCESS: 'ACCEPT_SUCCESS',
    ACCEPT_FAILED: 'ACCEPT_FAILED',

    BLOCK_STARTED: 'BLOCK_STARTED',
    BLOCK_SUCCESS: 'BLOCK_SUCCESS',
    BLOCK_FAILED: 'BLOCK_FAILED',

    UNBLOCK_STARTED: 'UNBLOCK_STARTED',
    UNBLOCK_SUCCESS: 'UNBLOCK_SUCCESS',
    UNBLOCK_FAILED: 'UNBLOCK_FAILED',

    MESSAGE_STARTED: 'MESSAGE_STARTED',
    MESSAGE_SUCCESS: 'MESSAGE_SUCCESS',
    MESSAGE_FAILED: 'MESSAGE_FAILED',

    DECLINE_STARTED:'DECLINE_STARTED',
    DECLINE_SUCCESS:'DECLINE_SUCCESS',
    DECLINE_FAILED:'DECLINE_FAILED',


    BLOCKER_RECIEVED: 'BLOCKER_RECIEVED',
    ACCEPTER_RECIEVED: 'ACCEPTER_RECIEVED',
    UNBLOCKER_RECIEVED: 'UNBLOCKER_RECIEVED',
    OFFERER_RECIEVED: 'OFFERER_RECIEVED',
    DECLINER_RECIEVED: 'DECLINER_RECIEVED',
    MESSANGER_RECIVED: 'MESSANGER_RECIVED'
}