export const actionTypes = {

    FETCH_HANGOUTS_STARTED: 'FETCH_HANGOUTS_STARTED',
    FETCH_HANGOUTS_SUCCESS: 'FETCH_HANGOUTS_SUCCESS',
    FETCH_HANGOUTS_FAILED: 'FETCH_HANGOUTS_FAILED',
    GOT_LOCAL_HANGOUTS: 'GOT_LOCAL_HANGOUTS',

    FIND_HANGOUTS: 'FIND_HANGOUTS',
    HANGOUTS_IS_ONLINE: 'HANGOUTS_IS_ONLINE',
    HANGOUTS_IS_OFFLINE: 'HANGOUTS_IS_OFFLINE',
    HANGOUTS_STATE_CHANGED: 'HANGOUTS_STATE_CHANGED',

    FETCH_USERS_STARTED: 'FETCH_USERS_STARTED',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILED: 'FETCH_USERS_FAILED',
    SELECTED_HANGOUTS: 'SELECTED_HANGOUTS',

    REMOVE_HANGOUT: 'REMOVE_HANGOUT',
    SELECT_HANGOUT:'SELECT_HANGOUT',

    FILTER_SET:'FILTER_SET'
  };
  