export const actionTypes = {
  //search
  SEARCH_INPUT_CHANGE: "SEARCH_INPUT_CHANGE",
  SEARCH_HANGOUT_STARTED: "SEARCH_HANGOUT_STARTED",
  SEARCH_HANGOUT_SUCCESS: "SEARCH_HANGOUT_SUCCESS",
  SEARCH_HANGOUT_FAILED: "SEARCH_HANGOUT_FAILED",

  //filter
  FILTER_INPUT_CHANGED: "FILTER_INPUT_CHANGED",

  SENDING_HANGOUT_STARTED: "SENDING_HANGOUT_STARTED",
  SENDING_HANGOUT_FULLFILLED: "SENDING_HANGOUT_FULLFILLED",

  MESSAGE_TEXT_CHANGED: "MESSAGE_TEXT_CHANGED",

  LOADED_HANGOUTS: "LOADED_HANGOUTS",
  LOADED_MESSAGES: "LOADED_MESSAGES",

  SELECTED_HANGOUT: "SELECTED_HANGOUT",
  CLEARED_HANGOUT: "CLEARED_HANGOUT",

  ERROR_RECIEVED: "ERROR_RECIEVED",
  ONLINE_STATE_CHANGED: "ONLINE_STATE_CHANGED",

  SERVER_MESSAGE_RECIEVED: "SERVER_MESSAGE_RECIEVED",

  MESSAGES_UPDATED: "MESSAGES_UPDATED",
  HANGOUTS_UPDATED: "HANGOUTS_UPDATED",
  HANGOUT_UPDATED: "HANGOUT_UPDATED",
  UNREAD_HANGOUTS_UPDATED: "UNREAD_HANGOUTS_UPDATED",
  //SOCKET

  CONNECTING: "CONNECTING",
  OPEN: "OPEN",
  CLOSING: "CLOSING",
  CLOSED: "CLOSED",
  SOCKET_READY: "SOCKET_READY",
  SOCKET_ERROR: "SOCKET_ERROR",
};
