export const actionTypes = {
  //fetch
  FETCH_HANGOUTS_STARTED: "FETCH_HANGOUTS_STARTED",
  FETCH_HANGOUTS_SUCCESS: "FETCH_HANGOUTS_SUCCESS",
  FETCH_HANGOUTS_FAILED: "FETCH_HANGOUTS_FAILED",

  //search
  SEARCH_INPUT_CHANGE: "SEARCH_INPUT_CHANGE",
  SEARCH_HANGOUT_STARTED: "SEARCH_HANGOUT_STARTED",
  SEARCH_HANGOUT_SUCCESS: "SEARCH_HANGOUT_SUCCESS",
  SEARCH_HANGOUT_FAILED: "SEARCH_HANGOUT_FAILED",
  //filter
  FILTER_INPUT_CHANGED: "FILTER_INPUT_CHANGED",

  SENDING_HANGOUT_STARTED: "SENDING_HANGOUT_STARTED",
  SENDING_HANGOUT_FULLFILLED: "SENDING_HANGOUT_FULLFILLED",

  MESSAGE_TEXT_CHANGED: "MESSAGE_TEXT_CHANGED",

  LOADED_HANGOUTS: "LOADED_HANGOUTS",
  LOADED_MESSAGES: "LOADED_MESSAGES",

  SELECTED_HANGOUT: "SELECTED_HANGOUT",
  CLEARED_HANGOUT: "CLEARED_HANGOUT",

  ERROR_RECIEVED: "ERROR_RECIEVED",
  ONLINE_STATE_CHANGED: "ONLINE_STATE_CHANGED",

  SERVER_MESSAGE_RECIEVED: "SERVER_MESSAGE_RECIEVED",

  MESSAGES_UPDATED: "MESSAGES_UPDATED",
  HANGOUTS_UPDATED: "HANGOUTS_UPDATED",
  HANGOUT_UPDATED: "HANGOUT_UPDATED",
  UNREAD_HANGOUTS_UPDATED: "UNREAD_HANGOUTS_UPDATED",
  //SOCKET

  SOCKET_CONNECTION_STATE_CHANGED: "SOCKET_CONNECTION_STATE_CHANGED",

  SOCKET_ERROR: "SOCKET_ERROR",

  //user siged out
  SET_HANGOUT_TO_INIT_STATE: "SET_HANGOUT_TO_INIT_STATE",
  SET_BROWSER_ID: "SET_BROWSER_ID",

  ON_USER_CLIENT_COMMAND: "ON_USER_CLIENT_COMMAND",
  ON_SOCKET_MESSAGE: "ON_SOCKET_MESSAGE",

  INVITE_GUEST: "INVITE_GUEST",

  MESSAGE_FOR_GUEST_CHANGED: "MESSAGE_FOR_GUEST_CHANGED",

  GUEST_EMAIL_CHANGED: "GUEST_EMAIL_CHANGED",

  INVITE_AS_GUEST_STARTED: "INVITE_AS_GUEST_STARTED",
  INVITE_AS_GUEST_SUCCESS: "INVITE_AS_GUEST_SUCCESS",
  INVITE_AS_GUEST_FAILED: "INVITE_AS_GUEST_FAILED",
  VALIDATED_GUEST_EMAIL_FORMAT: "VALIDATED_GUEST_EMAIL_FORMAT",
};
