export const actionTypes = {
    SENDING_HANGOUT_STARTED:'SENDING_HANGOUT_STARTED',
    SENDING_HANGOUT_FULLFILLED:'SENDING_HANGOUT_FULLFILLED',
    MESSAGE_TEXT_CHANGED:'MESSAGE_TEXT_CHANGED',

    LOAD_HANGOUTS: 'LOAD_HANGOUTS',
    LOADED_MESSAGES: 'LOADED_MESSAGES',
 
    SEARCH_INPUT_CHANGE: 'SEARCH_INPUT_CHANGE',
    SELECTED_HANGOUT: 'SELECTED_HANGOUT',
    CLEARED_HANGOUT:'CLEARED_HANGOUT',
    FETCH_HANGOUT_STARTED: 'FETCH_HANGOUT_STARTED',
    FETCH_HANGOUT_SUCCESS: 'FETCH_HANGOUT_SUCCESS',
    FETCH_HANGOUT_FAILED: 'FETCH_HANGOUT_FAILED',
    ERROR_RECIEVED:'ERROR_RECIEVED',
    ONLINE_STATE_CHANGED: 'ONLINE_STATE_CHANGED',

    SERVER_MESSAGE_RECIEVED:'SERVER_MESSAGE_RECIEVED',

    
    MESSAGES_UPDATED:'MESSAGES_UPDATED',
    HANGOUTS_UPDATED:'HANGOUTS_UPDATED',
    HANGOUT_UPDATED:'HANGOUT_UPDATED',
    UNREAD_HANGOUTS_UPDATED:'UNREAD_HANGOUTS_UPDATED',
    //SOCKET

    CONNECTING:'CONNECTING',
    OPEN:'OPEN',
    CLOSING:'CLOSING',
    CLOSED:'CLOSED',
    SOCKET_READY:'SOCKET_READY',
    SOCKET_ERROR:'SOCKET_ERROR'

}