export default {
  INITIALIZED_VIDEO_OFFER: "INITIALIZED_VIDEO_OFFER",
  CONNECTION_STATE_CHANGED: "CONNECTION_STATE_CHANGED",
  ICE_CONNECTION_STATE_CHANGED: "ICE_CONNECTION_STATE_CHANGED",
  ICE_GATHERING_STATE_CHANGED: "ICE_GATHERING_STATE_CHANGED",
  ON_TRACK: "ON_TRACK",
};
