module.exports = hangoutStates = {
  INVITER: "INVITER",
  ACCEPTER: "ACCEPTER",
  DECLINER: "DECLINER",
  BLOCKER: "BLOCKER",
  UNBLOCKER: "UNBLOCKER",
  MESSANGER: "MESSANGER",
  READER: "READER",
  // acknowlegement
  INVITED: "INVITED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
  BLOCKED: "BLOCKED",
  UNBLOCKED: "UNBLOCKED",
  MESSAGED: "MESSAGED",
  READ: "READ",
  READING: "READING",
};
